module.exports = {
  onBoarding: {
    LOGIN_SUCCESS: 'Login successfully.',
    CURRENT_PASSWORD: 'Current password is wrong',
    PASSWORD_CHANGED: 'Password changed successfully.',
    WRONG_CREDENTIALS: 'Account not found',
    WRONG_PASSWORD: 'Wrong password.',
    USERNAME_INACTIVE: 'Account is not active. Please contact to admin.',
    PAYLOAD_MISSING: 'Payload missing.',
    ACCOUNT_NOT_FOUND: 'Account not found.',
    EMAIL_NOT_FOUND: 'Email address not found.',
    VERIFICATION_CODE_SENT: 'Please check your email for the password reset link.',
    WRONG_VERIFICATION_CODE: 'Verification code is incorrect.',
    PASSWORD_RESET: 'Password reset successfully.',
    EMAIL_EXIST: 'Email already exist.',
    STATUS_CHANGED: 'Status changed successfully',
    APPROVALSTATUS: 'approvalStatus changed successfully',
    USER_DELETED: 'User deleted successfully.',
    EMAIL_REQUIRED: 'Email required.',
    PASSWORD_REQUIRED: 'Password required',
    ONLY_USER_LOGIN: 'Unauthorized access: Admin login detected.',
    PROFILE_UPDATED: 'Profile updated successfully.',
    USER_ADDED: 'User added successfully.',
    TOKEN_VALID: 'This token will valid for 10 hours only.',
    INVALID_ID: 'Invalid id.',
    NOT_VERIFIED: 'Please verify your email first.',
    EMAIL_AVAILABLE: 'You can use this email.',
    EMAIL_TAKEN: 'Email is already in use.',
    OTP_MATCHED: 'Verification code matched',
    INVALID_OTP: 'Verification code not matched',
    OTP_SENT: 'Verification code sent successfully',
    ID_REQUIRED: 'Id required',
    OTP_REQUIRED: 'Verification code required',
    INVALID_EMAIL: 'Invalid email.',
    FETCHED_SUCCESS: 'Data fetch Successfully',
    SUCCESSFULLY_REGISTERED: 'User successfully registered',
    USER_NOT_FOUND: 'User not found',
    NOT_FOUND: 'Either email or password is incorrect',
    NOT_AUTHORIZED: 'You are not authorized user for this portal.',
    ONLY_ADMIN_LOGIN: 'Unauthorized access: User login detected.',
    UPDATED: 'User Details updated successfully',
    ERROR: 'Something Went wrong',
    USER_NOT_VERIFIED: 'Please verify your email first.',
    OTP_NULL: 'OTP has expired',
    WRONG_EMAIL: 'Invalid email',
  },
  COMMON: {
    SUCCESS: 'Success',
    SERVER_ERROR: 'Something Went Wrong. Please try again.',
    UNAUTHORIZED: 'You are not authorized to perform this operation',
    STATUS_CHANGED: 'Status Change Successfully',
    ID_REQUIRED: 'Id required',
    INVALID_ID: 'Invalid Id',
    PAYLOAD_MISSING: 'Payload missing.',
  },
  CON: 'Payload missing.',
  category: {
    ALREADY_EXIST: 'Category already exists.',
    CREATED: 'Category created successfully.',
    STATUS_CHANGED: 'Category status changed successfully.',
    DELETED: 'Category deleted successfully.',
  },
  Feedback: {
    NOT_CREATED: 'Feedback could not be created.',
    CREATED: 'Feedback submitted successfully.',
    ID_REQUIRED: 'Feedback ID is required.',
    DETAIL_FETCHED: 'Feedback details fetched successfully.',
    NOT_FOUND: 'Feedback not found.',
    UPDATED: 'Feedback updated successfully.',
    DELETED: 'Feedback deleted successfully.',
    LISTING: 'Feedback fetched successfully.',
    STATUS_CHANGED: 'Feedback status changed successfully.',
    NOT_FOUND_EMAIL: 'The feedback has no email address to reply to.',
    REPLIED: 'Reply sent to the user successfully.',
  },
  CONTENT_MANAGEMENT: {
    ALREADY_EXIST: 'Content with this title already exists.',
    ADDED: 'Content added successfully.',
    NOT_FOUND: 'Content not found.',
    UPDATED: 'Content updated successfully.',
    TITLE_MISSING: 'Title is required.',
    FETCHED: 'Content fetched successfully.',
    DELETED: 'Content deleted successfully.',
  },
  FEATURE: {
    ALREADY_EXIST: 'Feature already exists.',
    CREATED: 'Feature created successfully.',
    NOT_FOUND: 'Feature not found.',
    FETCHED: 'Features fetched successfully.',
    UPDATED: 'Feature updated successfully.',
    DELETED: 'Feature deleted successfully.',
    NOT_IN_PLAN: 'Feature is associated with plans and cannot be deleted.',
  },
  PLAN: {
    PAYLOAD_MISSING: 'Plan payload missing.',
    RECOMMENDED_PLAN_ALREADY_EXIST: 'A recommended plan already exists.',
    FREE_PLAN_ALREADY_EXIST: 'A free plan already exists.',
    CREATE: 'Plan created successfully.',
    CREATED: 'Plan created successfully.',
    NOT_FOUND: 'Plan not found.',
    FETCH: 'Plans fetched successfully.',
    UPDATED: 'Plan updated successfully.',
    DELETED: 'Plan deleted successfully.',
    DELETION_ERR: 'Unable to delete plan. It is assigned to ',
    STATUS_CHANGED: 'Plan status changed successfully.',
  },
  SUBSCRIPTION: {
    NOT_FREE_PLAN: 'Free plan already purchased.',
    FETCH: 'Subscriptions fetched successfully.',
  },
  NOTIFICATIONS: {
    FETCHED: 'Notifications fetched successfully.',
    MARKED_READ: 'Notification marked as read.',
    ALL_READ: 'All notifications marked as read.',
    DISMISSED: 'Notification dismissed.',
    NOT_FOUND: 'Notification not found.',
    BROADCAST_SENT: 'Broadcast sent successfully.',
  },
  ROLES: {
    CREATED: 'Role created successfully.',
    FETCHED: 'Roles fetched successfully.',
    FETCHED_ONE: 'Role details fetched successfully.',
    UPDATED: 'Role updated successfully.',
    DELETED: 'Role deleted successfully.',
    STATUS_CHANGED: 'Role status changed successfully.',
    NOT_FOUND: 'Role not found.',
    ALREADY_EXIST: 'Role with this name already exists.',
    NAME_REQUIRED: 'Role name is required.',
    CANNOT_DELETE_SYSTEM: 'System roles cannot be deleted.',
    CANNOT_DEACTIVATE_SYSTEM: 'System roles cannot be deactivated.',
  },
  FAQ: {
    FETCHED: 'FAQs fetched successfully.',
    CATEGORIES_FETCHED: 'FAQ categories fetched successfully.',
    FETCHED: 'FAQs fetched successfully.',
    NOT_FOUND: 'FAQ not found.',
    CREATED: 'FAQ created successfully.',
    UPDATED: 'FAQ updated successfully.',
    DELETED: 'FAQ deleted successfully.',
    STATUS_CHANGED: 'FAQ status changed successfully.',
    ID_REQUIRED: 'FAQ ID is required.',
    PAYLOAD_MISSING: 'Category, question and answer are required.',
  },
  SETTINGS: {
    FETCHED: 'Settings fetched successfully.',
    UPDATED: 'Settings updated successfully.',
    NOT_FOUND: 'Settings not found.',
    PAYLOAD_MISSING: 'No settings provided to update.',
  },
};
